{{- if not .Values.is_dev }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: dsn # Key given to the secret to be created on the cluster
      remoteRef: 
        key: SENTRY_DSN # Key of the variable on Gitlab
    - secretKey: secretkey # Key given to the secret to be created on the cluster
      remoteRef: 
        key: DJANGO_SECRET_KEY # Key of the variable on Gitlab
{{ else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: django-secret
  namespace: vat-backend
data:
  secretkey: NEY0OENOY0U3YldjZFhXbzNHeWhIR3J5cmR3M3MyWms=
{{ end }}