apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  dataFrom:
  - extract:
      key: AISecrets
      property: rl_project_id
  - extract:
      key: AISecrets
      property: rl_trigger_token
  - extract:
      key: AISecrets
      property: slack_signing_secret
