apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: rl_project_id
      remoteRef: 
        key: RL_TRIGGER_PIPELINE_PROJECT_ID
    - secretKey: rl_trigger_token
      remoteRef: 
        key: RL_TRIGGER_PIPELINE_TOKEN
    - secretKey: slack_signing_secret
      remoteRef: 
        key: RL_TRIGGER_PIPELINE_SLACK_SIGNING_SECRET
