apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: password # Key given to the secret to be created on the cluster
      remoteRef: 
        key: KeycloakVatClientSecret # Key of the variable on Gitlab
