{{- if not .Values.is_dev }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  dataFrom:
    - extract:
        key: PostgresDjango
        property: username
    - extract:
        key: PostgresDjango
        property: password
{{ else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
data:
  password: N3RNN0daV3hIRFJudnpxMmJDalc0cnozTEFxWEpkaVY=
  username: bmFvdGg=
{{ end }}