apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  annotations:
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: alloy
    targetRevision: HEAD
    helm:
      releaseName: alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true