apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  annotations:
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: blog
    targetRevision: HEAD
    helm:
      releaseName: blog
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true