apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager2
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: cert-manager
    targetRevision: HEAD
    helm:
      releaseName: cert-manager
  destination:
    name: hetzner-k8s
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true