apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fileserver
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: fileserver
    targetRevision: HEAD
    helm:
      releaseName: fileserver
  destination:
    server: https://kubernetes.default.svc
    namespace: fileserver
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
