apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: image-updater
    targetRevision: HEAD
    helm:
      releaseName: image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
