apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner2
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: local-path-provisioner
    targetRevision: HEAD
    helm:
      releaseName: local-path-provisioner
  destination:
    name: hetzner-k8s
    namespace: local-path-provisioner
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true