apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: mattermost
    targetRevision: HEAD
    helm:
      releaseName: mattermost
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
