apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: postgres
    targetRevision: HEAD
    helm:
      releaseName: postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true