apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: rag
    targetRevision: HEAD
    helm:
      releaseName: rag
  destination:
    server: https://kubernetes.default.svc
    namespace: rag
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true