apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: renovate
    targetRevision: HEAD
    helm:
      releaseName: renovate
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true