apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vat-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=ghcr.io/berlinunited/django_backend
    argocd-image-updater.argoproj.io/myalias.update-strategy: newest-build
spec:
  project: default
  source:
    repoURL: 'git@github.com:Visual-Analytics-Toolbox/VAT-Deployments.git'
    path: vat-backend
    targetRevision: HEAD
    helm:
      releaseName: vat-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: vat-backend
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true