{{- if not .Values.is_dev }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: password
      remoteRef: 
        key: PostgresDjangoPassword
    - secretKey: username
      remoteRef: 
        key: PostgresDjangoUsername
{{ else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
data:
  password: N3RNN0daV3hIRFJudnpxMmJDalc0cnozTEFxWEpkaVY=
  username: bmFvdGg=
{{ end }}