apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: accessKeyID # Key given to the secret to be created on the cluster
      remoteRef: 
        key: MINIO_PYROSCOPE_USER # Key of the variable on Gitlab
    - secretKey: accessKeySecret # Key given to the secret to be created on the cluster
      remoteRef: 
        key: MINIO_PYROSCOPE_PASSWORD # Key of the variable on Gitlab  
