apiVersion: v1
kind: Service
metadata:
  name: mailman-core
spec:
  selector:
    app: mailman-core
  ports:
    - name: api
      port: 8001
      targetPort: 8001
    - name: lmtp
      port: 8024
      targetPort: 8024