apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailman-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailman-web
  template:
    metadata:
      labels:
        app: mailman-web
    spec:
      containers:
      - name: mailman-web
        image: maxking/mailman-web:rolling
        
        env:
        - name: DATABASE_TYPE
          value: "postgres"
        - name: SERVE_FROM_DOMAIN
          value: "maillist.berlin-united.com"
        - name: UWSGI_STATIC_MAP
          value: "/static=/opt/mailman-web-data/static"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "DATABASE_URL"
        - name: MAILMAN_CORE_ENDPOINT
          value: "http://mailman-core:8001"
        - name: HYPERKITTY_API_KEY
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "HYPERKITTY_API_KEY"
        - name: MAILMAN_CORE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "MAILMAN_CORE_USER"
        - name: MAILMAN_CORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "MAILMAN_CORE_PASSWORD"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "SECRET_KEY"
        - name: MAILMAN_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "MAILMAN_ADMIN_EMAIL"
        - name: MAILMAN_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "MAILMAN_ADMIN_USER"
        - name: SMTP_HOST
          value: "mailserver-docker-mailserver.mailserver.svc.cluster.local"
        - name: SMTP_PORT
          value: "587"  # Or 25 if you are staying internal and don't require STARTTLS
        - name: SMTP_HOST_USER
          value: "stella@berlin-united.com" # A valid account on your DMS
        - name: SMTP_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "SMTP_HOST_PASSWORD"
        - name: SMTP_SECURE_MODE
          value: "starttls"
        - name: DEFAULT_FROM_EMAIL
          value: "stella@berlin-united.com"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8080
          name: uwsgi
        volumeMounts:
        - name: web-data
          mountPath: /opt/mailman-web-data
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: mailman-web-pvc