apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: username
      remoteRef: 
        key: MAILMAN_POSTGRES_USER
    - secretKey: password
      remoteRef: 
        key: MAILMAN_POSTGRES_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef: 
        key: MAILMAN_POSTGRES_URL
    - secretKey: HYPERKITTY_API_KEY
      remoteRef: 
        key: HYPERKITTY_API_KEY
    - secretKey: MAILMAN_CORE_USER
      remoteRef: 
        key: MAILMAN_CORE_USER
    - secretKey: MAILMAN_CORE_PASSWORD
      remoteRef: 
        key: MAILMAN_CORE_PASSWORD
    - secretKey: SECRET_KEY
      remoteRef: 
        key: MAILMAIN_SECRET_KEY
    - secretKey: MAILMAN_ADMIN_EMAIL
      remoteRef: 
        key: MAILMAN_ADMIN_EMAIL
    - secretKey: MAILMAN_ADMIN_USER
      remoteRef: 
        key: MAILMAN_ADMIN_USER
    - secretKey: SMTP_HOST_PASSWORD
      remoteRef: 
        key: SMTP_HOST_PASSWORD
        