apiVersion: v2
name:  keycloak
description: Berlin United keycloak
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: keycloakx
    repository: https://codecentric.github.io/helm-charts
    version: 7.1.8
