{{- if not .Values.is_dev }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-mattermost
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-mattermost
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: mattermost.berlin-united.com
  dnsNames:
  - mattermost.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-mattermost
    kind: Issuer
{{ end }}
