apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mattermost-postgresql
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    deletionPolicy: "Retain"
    creationPolicy: Owner
  data:
  - secretKey: DB_CONNECTION_STRING
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: MATTERMOST_POSTGRES_CONNECTION_STRING
  - secretKey: password # Key given to the secret to be created on the cluster
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: MATTERMOST_POSTGRES_PASSWORD # Key of the variable on Gitlab
  - secretKey: username # Key given to the secret to be created on the cluster
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: MATTERMOST_POSTGRES_USER # Key of the variable on Gitlab