apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            key: token
            namespace: external-secrets
      projectID: "77789333"