apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: labelstudio-postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: password # Key given to the secret to be created on the cluster
      remoteRef: 
        key: LABELSTUDIO_POSTGRES_PASSWORD # Key of the variable on Gitlab
    - secretKey: username # Key given to the secret to be created on the cluster
      remoteRef: 
        key: LABELSTUDIO_POSTGRES_USER # Key of the variable on Gitlab 
