apiVersion: v2
name: CNPG
description: Berlin United Postgres Operator
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts/
    version: 0.27.0

