{{- if not .Values.is_dev }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-nextcloud
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-nextcloud
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: nextcloud.berlin-united.com
  dnsNames:
  - nextcloud.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-nextcloud
    kind: Issuer
{{ end }}