docker-mailserver:
  certificate: tls-cert-mailserver

  deployment:
    env:
      OVERRIDE_HOSTNAME: mail.berlin-united.com

  configMaps:
    # This creates the postfix-main.cf override
    postfix-main.cf: |
      transport_maps = pcre:/tmp/docker-mailserver/postfix-transport.pcre
      relay_domains = lists.berlin-united.com

    # This creates the actual routing rule
    postfix-transport.pcre: |
      /^.*@lists\.berlin-united\.com$/    lmtp:mailman-core-service:8024