# https://external-secrets.io/latest/guides/common-k8s-secret-types/
{{- if not .Values.is_dev }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-access
spec:
  secretStoreRef:
    kind: ClusterSecretStore  
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2

  data:
    - secretKey: .dockerconfigjson # Key given to the secret to be created on the cluster
      remoteRef: 
        key: GithubRegistry
{{ end }}
