apiVersion: v2
name:  labelstudio
description: Berlin United Labelstudio Instance
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: label-studio
    repository: https://charts.heartex.com/
    version: 1.11.7
