apiVersion: v2
name: mlflow
description: MLflow with remote Tracking Server, backend and artifact stores
type: application
version: 0.1.0
appVersion: 2.10.2

dependencies:
  - name: mlflow
    version: "1.8.0"
    repository: https://community-charts.github.io/helm-charts
