{{- if not .Values.is_dev }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  dataFrom:
  - extract:
      key: MinioSecret
      property: rootUser
  - extract:
      key: MinioSecret
      property: rootPassword
{{ else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-secret
data:
  rootUser: biBuYW90aAo=
  rootPassword: biBIQWsxMjM4NzY4YWRza2dsYXFBdnlkUUEK
{{ end }}
