apiVersion: v2
name: alloy
description: VAT tempo Helm Chart
type: application
version: 0.1.0
appVersion: "0.0.10"

dependencies:
  - name: tempo
    repository: https://grafana.github.io/helm-charts
    version: 1.24.4

