apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-basic-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: auth # Key given to the secret to be created on the cluster
      remoteRef: 
        key: MLFLOW_BASIC_AUTH # Key of the variable on Gitlab
