apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
spec:
  instances: 1

  storage:
    # does not really matter since our default storage class cant limit it
    size: 6Gi

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-envs

  monitoring:
    enablePodMonitor: true
